# Generated by Django 3.1.5 on 2021-03-10 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='reminder_date',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='user',
        ),
    ]
